# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YNgLEcVGssnNAFhcH7XF1IJ0MgLjl3EM
"""

import numpy as np
from scipy.stats import bernoulli
days = int(365)
count_eq = 0
count_uneq = 0
pr_h_bday = float(1/365)
pr_s_bday = float(1/365)
h_bday = np.zeros(shape = 365, dtype = int)
s_bday = np.zeros(shape = 365, dtype = int)
for j in range (0,365):
  count = 0
  while count!=1:
    count = 0
    h_bday = bernoulli.rvs(size = days, p = pr_h_bday)
    for i in range (0, 365):
      if h_bday[i] == 1:
        count += 1
  #print('The simulation for Hamida\'s birthday is:\n',h_bday)
  count = 0
  while count!=1:
    count = 0
    s_bday = bernoulli.rvs(size = days, p = pr_s_bday)
    for i in range (0, 365):
      if s_bday[i] == 1:
        count += 1
  #print('\nThe simulation for Savita\'s birthday is:\n',s_bday)
  count1 = 0
  for i in range (0,365):
    if(h_bday[i]==s_bday[i]):
      count1 += 1
  if(count1 == 365):
    count_eq += 1
  if(count1==363):
    count_uneq += 1

print('The simulated probability that Savita and Hamida have same birthdays is:',(count_eq/(365)))
print('The simulated probability that Savita and Hamida have different birthdays is:',(count_uneq/(365)))
print('\nThe actual probability that Savita and Hamida have same birthdays is:',(1/(365)))
print('The actual probability that Savita and Hamida have different birthdays is:',(364/(365)))