# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Rq8-xpuV81XfxxsGqMFD9TtcV_2TmqO
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import bernoulli

len = int(24)
pb = 2/3

dataset = bernoulli.rvs(size = len, p = pb)
sim_gr = np.nonzero(dataset == 1)
sim_prob_gr = np.size(sim_gr)/len
sim_prob_bl = 1 - sim_prob_gr
sim_bl = sim_prob_bl * len
print('Actual Number of Blue balls:',len*(1-pb))
print('Simulated Blue balls:',sim_bl)
print('Actual probability of Green Balls:',pb)
print('Probability of Green balls in simulation:',(sim_prob_gr))
print('Simulation: ',dataset)